// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Taske.Models
{
    public partial class Truck
    {
        [Key]
        public int id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal latitude { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal longitude { get; set; }
        public TimeSpan LastupdateDate { get; set; }
        public string DriverName { get; set; }
    }
}